[package]
name = "dvnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
idx-decoder = "0.0.2"
nalgebra = "0.19.0"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand = "0.8.5"